### ISSUE TITLE
KLIPS-Build fails on newer Kernels without CONFIG_USER_NS

### ISSUE THREAD

**Issue by tgeulig** [libreswan/libreswan#43]
My build on Linux 3.18 fails:

```
  CC [M]  ../modules/klips/pfkey_v2.o
../modules/klips/pfkey_v2.c: In function 'pfkey_create':
../modules/klips/pfkey_v2.c:750:14: error: incompatible types when assigning to type 'uint32_t' from type 'kuid_t'
scripts/Makefile.build:257: recipe for target '../modules/klips/pfkey_v2.o' failed
```

`HAVE_USER_NS` is only defined, if `CONFIG_USER_NS` is enabled in the kernel. IMO this is unecessary because `init_user_NS` and `from_kuid` are always defined.

So I propose the following change:
```
--- ipsec_kversion.h.orig       2015-11-06 08:51:07.167527341 +0100
+++ ipsec_kversion.h    2015-11-06 08:51:22.351489140 +0100
@@ -552,11 +552,8 @@
 # define DEFINE_RWLOCK(x) rwlock_t x = RW_LOCK_UNLOCKED
 #endif
 
-/* CONFIG_USER_NS is now on in Fedora 20 kernels */
 #if LINUX_VERSION_CODE >= KERNEL_VERSION(3, 5, 0)
-# if defined(CONFIG_USER_NS)
-#  define HAVE_USER_NS
-# endif
+# define HAVE_USER_NS
 #endif
 
 #endif /* _LIBRESWAN_KVERSIONS_H */
```

This works for me.

**Comment by letoams** [comment]
This was fixed slightly differently already.
