### ISSUE TITLE
‘NETDEV_UNREGISTER_FINAL’ undeclared (first use in this function)

### ISSUE THREAD

**Issue by jacusiel** [libreswan/libreswan#105]
Hello, I'm trying to compile on Centos 6.9 with kernel 2.6.32-696.1.1.el6.i686 
When I run make module, I get the following error:

/root/lintex/libreswan/modobj/ipsec_tunnel.c: In function ‘ipsec_device_event’:
/root/lintex/libreswan/modobj/ipsec_tunnel.c:1908: error: ‘NETDEV_UNREGISTER_FINAL’ undeclared (first use in this function)
/root/lintex/libreswan/modobj/ipsec_tunnel.c:1908: error: (Each undeclared identifier is reported only once
/root/lintex/libreswan/modobj/ipsec_tunnel.c:1908: error: for each function it appears in.)
/root/lintex/libreswan/modobj/ipsec_tunnel.c: In function ‘ipsec_tunnel_createnum’:
/root/lintex/libreswan/modobj/ipsec_tunnel.c:2143: error: implicit declaration of function ‘ipsec_alloc_netdev’
/root/lintex/libreswan/modobj/ipsec_tunnel.c:2144: error: ‘ipsec_tunnel_netdev_setup’ undeclared (first use in this function)
/root/lintex/libreswan/modobj/ipsec_tunnel.c: In function ‘ipsec_tunnel_deletenum’:
/root/lintex/libreswan/modobj/ipsec_tunnel.c:2231: error: ‘struct net_device’ has no member named ‘priv’
/root/lintex/libreswan/modobj/ipsec_tunnel.c:2232: error: ‘struct net_device’ has no member named ‘priv’
/root/lintex/libreswan/modobj/ipsec_tunnel.c: In function ‘ipsec_tunnel_cleanup_devices’:
/root/lintex/libreswan/modobj/ipsec_tunnel.c:2274: error: ‘struct net_device’ has no member named ‘priv’
/root/lintex/libreswan/modobj/ipsec_tunnel.c:2275: error: ‘struct net_device’ has no member named ‘priv’
make[3]: *** [/root/lintex/libreswan/modobj/ipsec_tunnel.o] Error 1
make[2]: *** [_module_/root/lintex/libreswan/modobj] Error 2
make[2]: Leaving directory `/usr/src/kernels/2.6.32-696.1.1.el6.i686'
make[1]: *** [module26] Error 2
make[1]: Leaving directory `/root/lintex/libreswan'
make: *** [module] Error 2

Any help will be much appreciated.

Thanks!

**Comment by bleve** [comment]
Klips won't work on rhel6 kernels and you should really run XFRM/IPsec aka netkey.

**Comment by jacusiel** [comment]
Thanks bleve for your hint. The thing is that I tried to use netkey, but I could't make it run. In my case, I have a pppoe link in one oend and the IP changes daily. I get the following error:

"connection1": We cannot identify ourselves with either end of this connection.  w.x.y.z or 0.0.0.0 are not usable

(w.x.y.z is the public fixed IP address of one end of the connection. The other end is a public IP that changes daily)

Thanks for any help you can give me

**Comment by bleve** [comment]
you can add networkmanager dispatcher script which restarts your ipsec when ip changes.

**Comment by mcr** [comment]
jacusiel <notifications@github.com> wrote:
    > "connection1": We cannot identify ourselves with either end of this
    > connection. w.x.y.z or 0.0.0.0 are not usable

This is not related to netkey or KLIPS.  Running KLIPS won't help you.
The problem is that libreswan does not know how to orient the connection.
You'd have to post more information.

--
]               Never tell me the odds!                 | ipv6 mesh networks [
]   Michael Richardson, Sandelman Software Works        | network architect  [
]     mcr@sandelman.ca  http://www.sandelman.ca/        |   ruby on rails    [

**Comment by jacusiel** [comment]
I don't use networkmanager, but I can put a script into /etc/ppp/ip-up.local
what you are proposing me is to build a script to put my new local ip into connection1.conf file and restart ipsec? Is there other way to do that?

**Comment by bleve** [comment]
left=%defaultroute should work for you.

**Comment by jacusiel** [comment]
Great! Now it works on the side of the VPN with the variable IP. On the other side I had to use %any. U put auto=add, but it keeps waiting.

**Comment by letoams** [comment]
On Tue, 13 Jun 2017, jacusiel wrote:

> Great! Now it works on the side of the VPN with the variable IP. On the other side I had to use %any. U put auto=add, but it keeps
> waiting.

auto=add means "load the connection and respond when the other end initiates"

auto=start means "load and initiate the connection"

auto=ondemand means "load the connection and trigger the connection when
packet flow matching the connection is attempted"

Paul

**Comment by letoams** [comment]
On Tue, 13 Jun 2017, jacusiel wrote:

> Thanks bleve for your hint. The thing is that I tried to use netkey, but I could't make it run. In my case, I have a pppoe link in
> one oend and the IP changes daily. I get the following error:
> 
> "connection1": We cannot identify ourselves with either end of this connection. w.x.y.z or 0.0.0.0 are not usable
> 
> (w.x.y.z is the public fixed IP address of one end of the connection. The other end is a public IP that changes daily)

Using left=%defaultroute will pick up the right IP. Whenever your
network topology changes, run "ipsec whack --listen" for libreswan
to re-read the network information and update the "%defaultroute"
value.

Paul

**Comment by jacusiel** [comment]
I'm getting closer. If I run ipsec verify everything look good but:

Checking 'prelink' command does not interfere with FIPS	[PRESENT]

[PRESENT] is in yellow so I don't know it's good or bad. Should I do something?

**Comment by letoams** [comment]
If you don't run your server in FIPS mode, you can ignore it

**Comment by jacusiel** [comment]
Thanks all for your help! My server wasn't receiving the connection request because there was now access on iptables. Now the tunnel is established, but traffic doesn't go through. I guess the routes are missing. I keep looking

**Comment by letoams** [comment]
On Tue, 13 Jun 2017, jacusiel wrote:

> Thanks all for your help! My server wasn't receiving the connection request because there was now access on iptables. Now the
> tunnel is established, but traffic doesn't go through. I guess the routes are missing. I keep looking

There are no routes with netkey. You can check if the tunnel is up
using: ipsec whack --trafficstatus

Most likely is that you are NAT'ing packets meant for the IPsec
tunnel so that they don't match the tunnel source-dest anymore.

If you have a tunnel from 10.1.2.0/24 to 192.168.1.0/24 and you
run NAT on the ipsec gateway, you need something like:

iptables -t nat -I POSTROUTING -s 10.1.2.0/24 -d 192.168.1.0/24 -j RETURN

See also https://libreswan.org/wiki/FAQ#NAT_.2B_IPsec_is_not_working

Paul

**Comment by jacusiel** [comment]
Thank you bleve and Paul for your help. Now it's working fine. Still have to solve some routes issues because the VPN server is not the default router. I was missing the following:

%defaultroute as left (or right) parameter in the variable IP end
%any as left (or right) parameter in the fixed IP end
auto=add for the server with the fixed IP to wait for the connection
Something was missing in the firewall configuration that had to solve.

**Comment by lucize** [comment]
@letoams @bleve 

I'm having the same error on kernel 4.19.x but it's working on 4.14

```
CFLAGS="-Os -pipe -march=pentium4 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap/home/build/openwrt/build_dir/target-i386_pentium4_musl/libreswan-3.27:libreswan-3.27 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -Wno-error=format-nonliteral  -I/home/build/openwrt/staging_dir/target-i386_pentium4_musl/usr/include -I/home/build/openwrt/staging_dir/target-i386_pentium4_musl/include -I/home/build/openwrt/staging_dir/toolchain-i386_pentium4_gcc-7.4.0_musl/usr/include -I/home/build/openwrt/staging_dir/toolchain-i386_pentium4_gcc-7.4.0_musl/include/fortify -I/home/build/openwrt/staging_dir/toolchain-i386_pentium4_gcc-7.4.0_musl/include " CXXFLAGS="-Os -pipe -march=pentium4 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap/home/build/openwrt/build_dir/target-i386_pentium4_musl/libreswan-3.27:libreswan-3.27 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -Wno-error=format-nonliteral  -I/home/build/openwrt/staging_dir/target-i386_pentium4_musl/usr/include -I/home/build/openwrt/staging_dir/target-i386_pentium4_musl/include -I/home/build/openwrt/staging_dir/toolchain-i386_pentium4_gcc-7.4.0_musl/usr/include -I/home/build/openwrt/staging_dir/toolchain-i386_pentium4_gcc-7.4.0_musl/include/fortify -I/home/build/openwrt/staging_dir/toolchain-i386_pentium4_gcc-7.4.0_musl/include " LDFLAGS="-L/home/build/openwrt/staging_dir/target-i386_pentium4_musl/usr/lib -L/home/build/openwrt/staging_dir/target-i386_pentium4_musl/lib -L/home/build/openwrt/staging_dir/toolchain-i386_pentium4_gcc-7.4.0_musl/usr/lib -L/home/build/openwrt/staging_dir/toolchain-i386_pentium4_gcc-7.4.0_musl/lib -znow -zrelro " make --jobserver-fds=3,4 -j -C /home/build/openwrt/build_dir/target-i386_pentium4_musl/libreswan-3.27/. AR="i486-openwrt-linux-musl-gcc-ar" AS="i486-openwrt-linux-musl-gcc -c -Os -pipe -march=pentium4 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap/home/build/openwrt/build_dir/target-i386_pentium4_musl/libreswan-3.27:libreswan-3.27 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -Wno-error=format-nonliteral" LD=i486-openwrt-linux-musl-ld NM="i486-openwrt-linux-musl-gcc-nm" CC="i486-openwrt-linux-musl-gcc" GCC="i486-openwrt-linux-musl-gcc" CXX="i486-openwrt-linux-musl-g++" RANLIB="i486-openwrt-linux-musl-gcc-ranlib" STRIP=i486-openwrt-linux-musl-strip OBJCOPY=i486-openwrt-linux-musl-objcopy OBJDUMP=i486-openwrt-linux-musl-objdump SIZE=i486-openwrt-linux-musl-size CROSS="i486-openwrt-linux-musl-" ARCH="i386" WERROR_CFLAGS=" " USE_DNSSEC=false USE_LINUX_AUDIT=false USE_LABELED_IPSEC=false USE_NM=false USE_LIBCURL=false USE_GLIBC_KERN_FLIP_HEADERS=true USE_XAUTHPAM=false USE_FIPSCHECK=false USE_LIBCAP_NG=false USE_SYSTEMD_WATCHDOG=false INC_USRLOCAL="/usr" FINALRUNDIR="/var/run/pluto" K_VER="4.19.34" LINUX_RELEASE="1" KERNELSRC="/home/build/openwrt/build_dir/target-i386_pentium4_musl/linux-x86_generic/linux-4.19.34" module;
[...]
Building module for a 2.6 kernel
[...]
make -C /home/build/openwrt/build_dir/target-i386_pentium4_musl/linux-x86_generic/linux-4.19.34  LINUX_VERSION_CODE=4.19.34 BUILDDIR=/home/build/openwrt/build_dir/target-i386_pentium4_musl/libreswan-3.27/modobj SUBDIRS=/home/build/openwrt/build_dir/target-i386_pentium4_musl/libreswan-3.27/modobj INITSYSTEM=systemd MODULE_DEF_INCLUDE=/home/build/openwrt/build_dir/target-i386_pentium4_musl/libreswan-3.27/packaging/linus/config-all.h MODULE_DEFCONFIG=/home/build/openwrt/build_dir/target-i386_pentium4_musl/libreswan-3.27/linux/net/ipsec/defconfig  MODULE_EXTRA_INCLUDE= ARCH=i386 V=s modules
[...]
/home/build/openwrt/build_dir/target-i386_pentium4_musl/libreswan-3.27/modobj/ipsec_tunnel.c: In function 'ipsec_device_event':
/home/build/openwrt/build_dir/target-i386_pentium4_musl/libreswan-3.27/modobj/ipsec_tunnel.c:1907:7: error: 'NETDEV_UNREGISTER_FINAL' undeclared (first use in this function); did you mean 'NETDEV_UNREGISTER'?
  case NETDEV_UNREGISTER_FINAL:
       ^~~~~~~~~~~~~~~~~~~~~~~
       NETDEV_UNREGISTER
/home/build/openwrt/build_dir/target-i386_pentium4_musl/libreswan-3.27/modobj/ipsec_tunnel.c:1907:7: note: each undeclared identifier is reported only once for each function it appears in

```
I tried to pass the `LINUX_VERSION_CODE=4.19.34` but doesn't seems to help
