### ISSUE TITLE
libreswan-5.2 doesn't compile with curl 8.14.1

### ISSUE THREAD

**Issue by vgnx** [libreswan/libreswan#2319]
### Please Tell Us About Your System

Fresh Archlinux install - Linux 6.15.3-arch1-1

```
curl --version
curl 8.14.1 (x86_64-pc-linux-gnu) libcurl/8.14.1 OpenSSL/3.5.0 zlib/1.3.1 brotli/1.1.0 zstd/1.5.7 libidn2/2.3.7 libpsl/0.21.5 libssh2/1.11.1 nghttp2/1.66.0 nghttp3/1.10.1
```

```
gcc --version
gcc (GCC) 15.1.1 20250425
```

```
make --version
GNU Make 4.4.1
```

### IKE Version

- [ ] IKEv1
- [ ] IKEv2

### Protocol

- [ ] ESP
- [ ] AH

### Is IPsec or VTI involved?

- [ ] IPsec Interface
- [ ] VTI

### What happened?

While installing it using AUR, I get the following compilation error

```
/usr/src/debug/libreswan/src/libreswan-5.2/programs/pluto/fetch.c: In function ‘fetch_curl’:
/usr/src/debug/libreswan/src/libreswan-5.2/programs/pluto/fetch.c:120:9: error: call to ‘_curl_easy_setopt_err_long’ declared with attribute warning: curl_easy_setopt expects a long argument [-Werror=attribute-warning]
  120 |         CESO(CURLOPT_NOSIGNAL, 1);      /* work around for libcurl signal bug */
      |         ^
lto1: all warnings being treated as errors
make[4]: *** [/tmp/ccD65pfQ.mk:16: /tmp/cco8OHdN.ltrans7.ltrans.o] Error 1
lto-wrapper: fatal error: make returned 2 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make[3]: *** [../../mk/program.mk:65: pluto] Error 1
make[2]: *** [../../mk/targets.mk:84: all] Error 2
make[1]: *** [../mk/targets.mk:84: recursive-all] Error 2
make: *** [/usr/src/debug/libreswan/src/libreswan-5.2/mk/targets.mk:84: recursive-all] Error 2
==> ERROR: A failure occurred in build().
/usr/share/makepkg/util/message.sh: line 51: QUIET: unbound variable
/usr/bin/makepkg: line 133: logpipe: unbound variable
 -> error making: libreswan-exit status 1
 -> Failed to install the following packages. Manual intervention is required:
libreswan - exit status 1

```

### Your configuration

```shell

```

### Relevant log output

```shell

```

**Comment by cagney** [comment]
Can you please try mainline?

The file `pluto/fetch.c` was updated then moved to `_import_crl/`

**Comment by cagney** [comment]
The newest version of curl in the build farm is only `curl-8.11.1-4.fc42.x86_64`

**Comment by cagney** [comment]
probably [the fix](https://github.com/curl/curl/commit/79b4e56b3f30dc1ac28a81128a07d27338e5219e#diff-de9469952f122a68a6a3a5f14b5931d947e25ef4fcaab51d77d404bf709c97ad)

**Comment by vgnx** [comment]
Thank you for you answer

I confirm you that downgrading curl to 8.11.1-x solves this error.
Now I have another error that is not related to this issue (xmlto validation error) so I'll not share it here

**Comment by cagney** [comment]
it's still in mainline.

On x86-64 Linux, which I gather has a 32-bit little-endian int:
- `curl_easy_setopt(..., CURLOPT_NOSIGNAL, 1)` pushes a 32-bit little-endian `int` on the stack
- `Curl_vsetopt()` then reads the value as 64-bits little-endian value using `va_arg(param, long)`
because it's LE, the long is 0xxxxx0001, i.e., the LSB is still set
-  the long is then assigned to `data->set.no_signal` which seems to be a `unsigned int no_signal:1` (see BIT())
because the type is `unsigned int` the value is truncated down to `1` (if it were `bool`, any non-zero value would have been converted to `true`)

The same code on a 64-bit BE ABI, would end up with `.no_signal` assigned something random from the stack.

**Comment by cagney** [comment]
fixed in 5.3
