### ISSUE TITLE
Multiple compile errors with gcc (GCC) 7.1.1 20170528

### ISSUE THREAD

**Issue by abique** [libreswan/libreswan#104]
Hi guys,

Could you please try to build libreswan with the latest version of gcc?
This one is reporting a few warning which turns to become errors.

Many thanks,
Alex.

**Comment by abique** [comment]
```
cc -O2 -pipe -fstack-protector-strong -Wno-error=sign-compare -Wno-error=unused-const-variable  -I/home/abique/develop/aur/libreswan/src/libreswan-3.20/lib/libcrypto/libsha2 -I/home/abique/develop/aur/libreswan/src/libreswan-3.20/lib/libcrypto/libaes_xcbc -I/home/abique/develop/aur/libreswan/src/libreswan-3.20/ports/linux/include -I. -I/home/abique/develop/aur/libreswan/src/libreswan-3.20/linux/net/ipsec -I/home/abique/develop/aur/libreswan/src/libreswan-3.20/linux/include -I/home/abique/develop/aur/libreswan/src/libreswan-3.20 -DPFKEYV2 -DKLIPS -I/usr/include/nss -I/usr/include/nspr -I/home/abique/develop/aur/libreswan/src/libreswan-3.20/include -I/home/abique/develop/aur/libreswan/src/libreswan-3.20/ports/linux/include -std=gnu99 -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-all -fno-strict-aliasing -fPIE -DPIE -DDNSSEC -DKLIPS -DLIBCURL -DUSE_SYSTEMD_WATCHDOG -DHAVE_NM -DXAUTH_HAVE_PAM -DUSE_MD5 -DUSE_SHA2 -DUSE_SHA1 -DUSE_AES -DUSE_3DES -DUSE_CAMELLIA -DUSE_SERPENT -DUSE_TWOFISH -DUSE_CAST -DUSE_RIPEMD -DFIPSPRODUCTCHECK=\"/etc/system-fips\" -DIPSEC_CONF=\"/etc/ipsec.conf\" -DIPSEC_CONFDDIR=\"/etc/ipsec.d\" -DIPSEC_NSSDIR=\"/etc/ipsec.d\" -DIPSEC_CONFDIR=\"/etc\" -DIPSEC_EXECDIR=\"/usr/lib/ipsec\" -DIPSEC_SBINDIR=\"/usr/bin\" -DIPSEC_VARDIR=\"/var\" -DPOLICYGROUPSDIR=\"/etc/ipsec.d/policies\" -DIPSEC_SECRETS_FILE=\"/etc/ipsec.secrets\" -DFORCE_PR_ASSERT -DRETRANSMIT_INTERVAL_DEFAULT="500" -DUSE_FORK=1 -DUSE_VFORK=0 -DUSE_DAEMON=0 -DUSE_PTHREAD_SETSCHEDPRIO=1 -DGCC_LINT -DALLOW_MICROSOFT_BAD_PROPOSAL -Werror -Wall -Wextra -Wformat -Wformat-nonliteral -Wformat-security -Wundef -Wmissing-declarations -Wredundant-decls -Wnested-externs  -DNSS_REQ_AVA_COPY -I/home/abique/develop/aur/libreswan/src/libreswan-3.20/lib/libcrypto/libsha2 -I/home/abique/develop/aur/libreswan/src/libreswan-3.20/lib/libcrypto/libaes_xcbc -I/home/abique/develop/aur/libreswan/src/libreswan-3.20/ports/linux/include -I. -I/home/abique/develop/aur/libreswan/src/libreswan-3.20/linux/net/ipsec -I/home/abique/develop/aur/libreswan/src/libreswan-3.20/linux/include -I/home/abique/develop/aur/libreswan/src/libreswan-3.20 -DPFKEYV2 -DKLIPS -I/usr/include/nss -I/usr/include/nspr -I/home/abique/develop/aur/libreswan/src/libreswan-3.20/include -I/home/abique/develop/aur/libreswan/src/libreswan-3.20/ports/linux/include -std=gnu99 -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-all -fno-strict-aliasing -fPIE -DPIE -DDNSSEC -DKLIPS -DLIBCURL -DUSE_SYSTEMD_WATCHDOG -DHAVE_NM -DXAUTH_HAVE_PAM -DUSE_MD5 -DUSE_SHA2 -DUSE_SHA1 -DUSE_AES -DUSE_3DES -DUSE_CAMELLIA -DUSE_SERPENT -DUSE_TWOFISH -DUSE_CAST -DUSE_RIPEMD -DFIPSPRODUCTCHECK=\"/etc/system-fips\" -DIPSEC_CONF=\"/etc/ipsec.conf\" -DIPSEC_CONFDDIR=\"/etc/ipsec.d\" -DIPSEC_NSSDIR=\"/etc/ipsec.d\" -DIPSEC_CONFDIR=\"/etc\" -DIPSEC_EXECDIR=\"/usr/lib/ipsec\" -DIPSEC_SBINDIR=\"/usr/bin\" -DIPSEC_VARDIR=\"/var\" -DPOLICYGROUPSDIR=\"/etc/ipsec.d/policies\" -DIPSEC_SECRETS_FILE=\"/etc/ipsec.secrets\" -DFORCE_PR_ASSERT -DRETRANSMIT_INTERVAL_DEFAULT="500" -DUSE_FORK=1 -DUSE_VFORK=0 -DUSE_DAEMON=0 -DUSE_PTHREAD_SETSCHEDPRIO=1 -DGCC_LINT -DALLOW_MICROSOFT_BAD_PROPOSAL -Werror -Wall -Wextra -Wformat -Wformat-nonliteral -Wformat-security -Wundef -Wmissing-declarations -Wredundant-decls -Wnested-externs  -DNSS_REQ_AVA_COPY -I/home/abique/develop/aur/libreswan/src/libreswan-3.20/ports/linux/include  \
	-MMD -MF ./version.d \
	-o ./version.o \
	-c /home/abique/develop/aur/libreswan/src/libreswan-3.20/OBJ.linux.x86_64/lib/libswan/version.c
In file included from /home/abique/develop/aur/libreswan/src/libreswan-3.20/linux/net/ipsec/pfkey_v2_parse.c:69:0:
/home/abique/develop/aur/libreswan/src/libreswan-3.20/linux/net/ipsec/pfkey_v2_parse.c: In function ‘pfkey_msg_parse’:
/home/abique/develop/aur/libreswan/src/libreswan-3.20/linux/include/libreswan/pfkey_debug.h:46:42: error: this statement may fall through [-Werror=implicit-fallthrough=]
 #define DEBUGGING(level, args ...)  { if (pfkey_lib_debug & (level)) { \
                                          ^
/home/abique/develop/aur/libreswan/src/libreswan-3.20/linux/net/ipsec/pfkey_v2_parse.c:1294:4: note: in expansion of macro ‘DEBUGGING’
    DEBUGGING(PF_KEY_DEBUG_PARSE_PROBLEM,
    ^~~~~~~~~
/home/abique/develop/aur/libreswan/src/libreswan-3.20/linux/net/ipsec/pfkey_v2_parse.c:1304:2: note: here
  case K_SADB_ACQUIRE:
  ^~~~

```

**Comment by abique** [comment]
```
cc -std=gnu99 -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-all -fno-strict-aliasing -fPIE -DPIE -DDNSSEC -DKLIPS -DLIBCURL -DUSE_SYSTEMD_WATCHDOG -DHAVE_NM -DXAUTH_HAVE_PAM -DUSE_MD5 -DUSE_SHA2 -DUSE_SHA1 -DUSE_AES -DUSE_3DES -DUSE_CAMELLIA -DUSE_SERPENT -DUSE_TWOFISH -DUSE_CAST -DUSE_RIPEMD -DFIPSPRODUCTCHECK=\"/etc/system-fips\" -DIPSEC_CONF=\"/etc/ipsec.conf\" -DIPSEC_CONFDDIR=\"/etc/ipsec.d\" -DIPSEC_NSSDIR=\"/etc/ipsec.d\" -DIPSEC_CONFDIR=\"/etc\" -DIPSEC_EXECDIR=\"/usr/lib/ipsec\" -DIPSEC_SBINDIR=\"/usr/bin\" -DIPSEC_VARDIR=\"/var\" -DPOLICYGROUPSDIR=\"/etc/ipsec.d/policies\" -DIPSEC_SECRETS_FILE=\"/etc/ipsec.secrets\" -DFORCE_PR_ASSERT -DRETRANSMIT_INTERVAL_DEFAULT="500" -DUSE_FORK=1 -DUSE_VFORK=0 -DUSE_DAEMON=0 -DUSE_PTHREAD_SETSCHEDPRIO=1 -DGCC_LINT -DALLOW_MICROSOFT_BAD_PROPOSAL -Werror -Wall -Wextra -Wformat -Wformat-nonliteral -Wformat-security -Wundef -Wmissing-declarations -Wredundant-decls -Wnested-externs -I/home/abique/develop/aur/libreswan/src/libreswan-3.20/ports/linux/include  -I/home/abique/develop/aur/libreswan/src/libreswan-3.20/programs/pluto/linux26 -I/home/abique/develop/aur/libreswan/src/libreswan-3.20/include -I/home/abique/develop/aur/libreswan/src/libreswan-3.20/lib/libcrypto -I/home/abique/develop/aur/libreswan/src/libreswan-3.20/linux/include    -DNETKEY_SUPPORT -DKERNEL26_HAS_KAME_DUPLICATES -DPFKEY -DKLIPS -DPFKEY          -DHAVE_LIBCAP_NG -I/usr/include/nss -I/usr/include/nspr -O2 -pipe -fstack-protector-strong -Wno-error=sign-compare -Wno-error=unused-const-variable -Wno-error=implicit-fallthrough  \
	-MMD -MF ./log.d \
	-o ./log.o \
	-c /home/abique/develop/aur/libreswan/src/libreswan-3.20/programs/pluto/log.c
/home/abique/develop/aur/libreswan/src/libreswan-3.20/programs/pluto/defs.c: In function ‘check_expiry’:
/home/abique/develop/aur/libreswan/src/libreswan-3.20/programs/pluto/defs.c:149:51: error: ‘%ld’ directive output may be truncated writing between 1 and 20 bytes into a region of size 15 [-Werror=format-truncation=]
   snprintf(buf, sizeof(buf), "warning (expires in %ld %s%s)",
                                                   ^~~
/home/abique/develop/aur/libreswan/src/libreswan-3.20/programs/pluto/defs.c:149:30: note: directive argument in the range [-9223372036854775808, 106751991167300]
   snprintf(buf, sizeof(buf), "warning (expires in %ld %s%s)",
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/stdio.h:939:0,
                 from /home/abique/develop/aur/libreswan/src/libreswan-3.20/programs/pluto/defs.c:23:
/usr/include/bits/stdio2.h:64:10: note: ‘__builtin___snprintf_chk’ output between 27 and 50 bytes into a destination of size 35
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc -std=gnu99 -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-all -fno-strict-aliasing -fPIE -DPIE -DDNSSEC -DKLIPS -DLIBCURL -DUSE_SYSTEMD_WATCHDOG -DHAVE_NM -DXAUTH_HAVE_PAM -DUSE_MD5 -DUSE_SHA2 -DUSE_SHA1 -DUSE_AES -DUSE_3DES -DUSE_CAMELLIA -DUSE_SERPENT -DUSE_TWOFISH -DUSE_CAST -DUSE_RIPEMD -DFIPSPRODUCTCHECK=\"/etc/system-fips\" -DIPSEC_CONF=\"/etc/ipsec.conf\" -DIPSEC_CONFDDIR=\"/etc/ipsec.d\" -DIPSEC_NSSDIR=\"/etc/ipsec.d\" -DIPSEC_CONFDIR=\"/etc\" -DIPSEC_EXECDIR=\"/usr/lib/ipsec\" -DIPSEC_SBINDIR=\"/usr/bin\" -DIPSEC_VARDIR=\"/var\" -DPOLICYGROUPSDIR=\"/etc/ipsec.d/policies\" -DIPSEC_SECRETS_FILE=\"/etc/ipsec.secrets\" -DFORCE_PR_ASSERT -DRETRANSMIT_INTERVAL_DEFAULT="500" -DUSE_FORK=1 -DUSE_VFORK=0 -DUSE_DAEMON=0 -DUSE_PTHREAD_SETSCHEDPRIO=1 -DGCC_LINT -DALLOW_MICROSOFT_BAD_PROPOSAL -Werror -Wall -Wextra -Wformat -Wformat-nonliteral -Wformat-security -Wundef -Wmissing-declarations -Wredundant-decls -Wnested-externs -I/home/abique/develop/aur/libreswan/src/libreswan-3.20/ports/linux/include  -I/home/abique/develop/aur/libreswan/src/libreswan-3.20/programs/pluto/linux26 -I/home/abique/develop/aur/libreswan/src/libreswan-3.20/include -I/home/abique/develop/aur/libreswan/src/libreswan-3.20/lib/libcrypto -I/home/abique/develop/aur/libreswan/src/libreswan-3.20/linux/include    -DNETKEY_SUPPORT -DKERNEL26_HAS_KAME_DUPLICATES -DPFKEY -DKLIPS -DPFKEY          -DHAVE_LIBCAP_NG -I/usr/include/nss -I/usr/include/nspr -O2 -pipe -fstack-protector-strong -Wno-error=sign-compare -Wno-error=unused-const-variable -Wno-error=implicit-fallthrough  \
	-MMD -MF ./state.d \
	-o ./state.o \
	-c /home/abique/develop/aur/libreswan/src/libreswan-3.20/programs/pluto/state.c
cc1: all warnings being treated as errors
make[3]: *** [../../../mk/depend.mk:28: defs.o] Error 1
make[3]: *** Waiting for unfinished jobs....
/home/abique/develop/aur/libreswan/src/libreswan-3.20/programs/pluto/connections.c: In function ‘fmt_policy_prio’:
/home/abique/develop/aur/libreswan/src/libreswan-3.20/programs/pluto/connections.c:2194:35: error: ‘%lu’ directive output may be truncated writing between 1 and 15 bytes into a region of size 8 [-Werror=format-truncation=]
   snprintf(buf, POLICY_PRIO_BUF, "%lu,%lu",
                                   ^~~
/home/abique/develop/aur/libreswan/src/libreswan-3.20/programs/pluto/connections.c:2194:34: note: directive argument in the range [0, 281474976710655]
   snprintf(buf, POLICY_PRIO_BUF, "%lu,%lu",
                                  ^~~~~~~~~
/home/abique/develop/aur/libreswan/src/libreswan-3.20/programs/pluto/connections.c:2194:34: note: directive argument in the range [0, 255]
In file included from /usr/include/stdio.h:939:0,
                 from /home/abique/develop/aur/libreswan/src/libreswan-3.20/programs/pluto/connections.c:34:
/usr/include/bits/stdio2.h:64:10: note: ‘__builtin___snprintf_chk’ output between 4 and 20 bytes into a destination of size 8
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by abique** [comment]
```
17-06-10 20:20:25 abique@knot:~> uname -a
Linux knot 4.11.3-1-ARCH #1 SMP PREEMPT Sun May 28 10:40:17 CEST 2017 x86_64 GNU/Linux
```

**Comment by Konfuz** [comment]
I am getting the same errors trying to compile using gcc 7.1.1 20170516 and it gradually gets worse when I try to ignore the warnings mentioned by abique. Next comes a pointer-compare error: 

```
libreswan-3.20/programs/pluto/plutoalg.c: In function ‘aalg_getbyname_ike’:
libreswan-3.20/programs/pluto/plutoalg.c:79:25: error: comparison between pointer and zero character constant [-Werror=pointer-compare]
  if (str == NULL || str == '\0')
                         ^~
libreswan-3.20/programs/pluto/plutoalg.c:79:21: note: did you mean to dereference the pointer?
  if (str == NULL || str == '\0')
                     ^
cc1: all warnings being treated as errors

```

Im not a very committed self-compiler so there might be user-error on my side, but I can reproduce and apparently im on the same system as abique: 
```
tabby% uname -a
Linux tabby 4.11.3-1-ARCH #1 SMP PREEMPT Sun May 28 10:40:17 CEST 2017 x86_64 GNU/Linux
tabby% gcc --version
gcc (GCC) 7.1.1 20170516
```

In the end i could successfully compile with <tt>-Wno-error</tt> and <tt>-Werror=implicit-fallthrough=0</tt> but it feels wrong...

**Comment by letoams** [comment]
On Wed, 14 Jun 2017, Timon Giese wrote:

> I am getting the same errors trying to compile using gcc 7.1.1 20170516 and it gradually gets worse when I try to ignore the
> warnings mentioned by abique. Next comes a pointer-compare error:
> 
> libreswan-3.20/programs/pluto/plutoalg.c: In function ‘aalg_getbyname_ike’:
> libreswan-3.20/programs/pluto/plutoalg.c:79:25: error: comparison between pointer and zero character constant [-Werror=pointer-c
> ompare]
>   if (str == NULL || str == '\0')
>                          ^~

The function aalg_getbyname_ike() no longer exists.

> In the end i could successfully compile with -Wno-error and -Werror=implicit-fallthrough=0 but it feels wrong...

We have a number of fallthrough cases. We always mark them with

 	/* FALL THROUGH */

to indicate it is intentional. If there is a gcc7 marker for that, we
could use it. Looking around, I find:

https://developers.redhat.com/blog/2017/03/10/wimplicit-fallthrough-in-gcc-7/

and:

https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html

Which seems to indicate that -Wimplicit-fallthrough=3 might do the right
thing, and our comments should match the regular expression.

If you find a fallthrough that would not have a matching comment, it is
a bug and we have to look at it and either fix the code or add the
comment.

I don't have a gcc7 system I can easilly test this on.

Paul

**Comment by abique** [comment]
Is it possible for you to bootstrap an archlinux container or vm?
That should not take long with lxc I think.

**Comment by abique** [comment]
You could also take the archlinux installer, boot qemu with it, install/update gcc in the live environment and try to build libreswan there.

**Comment by letoams** [comment]
On Wed, Jun 14, 2017 at 10:25:07AM -0400, Paul Wouters wrote:
> On Wed, 14 Jun 2017, Timon Giese wrote:
> 
> > I am getting the same errors trying to compile using gcc 7.1.1 20170516 and it gradually gets worse when I try to ignore the
> > warnings mentioned by abique. Next comes a pointer-compare error:
> > 
> > libreswan-3.20/programs/pluto/plutoalg.c: In function ‘aalg_getbyname_ike’:
> > libreswan-3.20/programs/pluto/plutoalg.c:79:25: error: comparison between pointer and zero character constant [-Werror=pointer-c
> > ompare]
> >   if (str == NULL || str == '\0')
> >                          ^~
>

before aalg_getbyname_ike was removed there was a fix for the above issue. 
https://github.com/libreswan/libreswan/commit/c65a002a7b4eb0aa1407c2759e1c721634c739c1
 
for Wimplicit-fallthrough=3 complaince 
I have a patch sitting around when I played with F26. It is attached here to test.
It could be applied, I haven't double checked it yet.

I used F26 gcc version 7.1.1 20170503 (Red Hat 7.1.1-1) (GCC)

> The function aalg_getbyname_ike() no longer exists.
> 
> > In the end i could successfully compile with -Wno-error and -Werror=implicit-fallthrough=0 but it feels wrong...
> 
> We have a number of fallthrough cases. We always mark them with
> 
> 	/* FALL THROUGH */
> 
> to indicate it is intentional. If there is a gcc7 marker for that, we
> could use it. Looking around, I find:
> 
> https://developers.redhat.com/blog/2017/03/10/wimplicit-fallthrough-in-gcc-7/
> 
> and:
> 
> https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html
> 
> Which seems to indicate that -Wimplicit-fallthrough=3 might do the right
> thing, and our comments should match the regular expression.
> 
> If you find a fallthrough that would not have a matching comment, it is
> a bug and we have to look at it and either fix the code or add the
> comment. 
> I don't have a gcc7 system I can easilly test this on.
> 
> Paul
> _______________________________________________
> Swan-dev mailing list
> Swan-dev@lists.libreswan.org
> https://lists.libreswan.org/mailman/listinfo/swan-dev

From 7e58ea548e33081e19643801f85d5781e7ea0435 Mon Sep 17 00:00:00 2001
From: Antony Antony <antony@phenome.org>
Date: Wed, 10 May 2017 19:29:19 +0200
Subject: [PATCH] building: fix -Wimplicit-fallthrough=3 warning for gcc 7.x

Details on -Wimplicit-fallthrough
https://developers.redhat.com/blog/2017/03/10/wimplicit-fallthrough-in-gcc-7/
---
 linux/net/ipsec/pfkey_v2_parse.c | 1 +
 programs/eroute/eroute.c         | 2 ++
 2 files changed, 3 insertions(+)

diff --git a/linux/net/ipsec/pfkey_v2_parse.c b/linux/net/ipsec/pfkey_v2_parse.c
index 363a5d6..247cd21 100644
--- a/linux/net/ipsec/pfkey_v2_parse.c
+++ b/linux/net/ipsec/pfkey_v2_parse.c
@@ -1302,6 +1302,7 @@ int pfkey_msg_parse(struct sadb_msg *pfkey_msg,
 				  pfkey_v2_sadb_type_string(pfkey_msg->
 							    sadb_msg_type));
 		}
+		/* FALLTHROUGH */
 	case K_SADB_ACQUIRE:
 	case K_SADB_REGISTER:
 	case K_SADB_EXPIRE:
diff --git a/programs/eroute/eroute.c b/programs/eroute/eroute.c
index fc9ec42..2b987b4 100644
--- a/programs/eroute/eroute.c
+++ b/programs/eroute/eroute.c
@@ -914,6 +914,7 @@ sa_build:
 				fprintf(stderr, "Mask not found.\n");
 				break;
 			}
+			/* FALLTHROUGH */
 		case EFAULT:
 			if ((action_type == EMT_SETEROUTE) ||
 			    (action_type == EMT_REPLACEROUTE)) {
@@ -924,6 +925,7 @@ sa_build:
 				fprintf(stderr, "Address not found.\n");
 				break;
 			}
+			/* FALLTHROUGH */
 		case EACCES:
 			fprintf(stderr, "access denied.  ");
 			if (getuid() == 0)
-- 
2.9.4

**Comment by letoams** [comment]
On Wed, 14 Jun 2017, Antony Antony wrote:

> for Wimplicit-fallthrough=3 complaince
> I have a patch sitting around when I played with F26. It is attached here to test.
> It could be applied, I haven't double checked it yet.

So I checked the eroute one, and cleaned up the break;s so it makes more
sense. The one in pfkey.c is weird:

diff --git a/linux/net/ipsec/pfkey_v2_parse.c
b/linux/net/ipsec/pfkey_v2_parse.c
index 363a5d6..247cd21 100644
--- a/linux/net/ipsec/pfkey_v2_parse.c
+++ b/linux/net/ipsec/pfkey_v2_parse.c
@@ -1302,6 +1302,7 @@ int pfkey_msg_parse(struct sadb_msg *pfkey_msg,
                                   pfkey_v2_sadb_type_string(pfkey_msg->
                                                             sadb_msg_type));
                 }
+               /* FALLTHROUGH */
         case K_SADB_ACQUIRE:
         case K_SADB_REGISTER:
         case K_SADB_EXPIRE:


That basically makes the resulting chunk of code work on _every_ case,
which leads to the question, why is it inside the switch().

A quick peek shows this goes at least as far back as openswan-2.3.x,
probably even further. So maybe Richard can answer this one :)

Paul

**Comment by abique** [comment]
I updated the pkgbuild for archlinux, with a lot of -Wno-error... :-1:

**Comment by letoams** [comment]
I committed this change for now to be able to compile on F26

**Comment by letoams** [comment]
all pending gcc 7.x issues are now fixed in 3.21
