### ISSUE TITLE
Build error 3.32

### ISSUE THREAD

**Issue by sirajka** [libreswan/libreswan#341]
Can't get Route Based VPN to work on 3.25 so I am trying to upgrade to XFRMi. Since 3.25 was latest package available, I have to build from source.  

Building 3.32 on `Amazon Linux 2 4.14.173-137.229.amzn2.x86_64`
Running 
`rpmbuild -ba packaging/rhel/7/libreswan.spec`
gives errors.

Any help would be most appreciated. 

```
/root/rpmbuild/BUILD/libreswan-3.32/lib/libswan/ike_alg_prf_ikev1_nss_ops.c:228:2: error: unknown type name 'CK_NSS_IKE1_APP_B_PRF_DERIVE_PARAMS'; did you mean 'CK_NSS_IKE1_PRF_DERIVE_PARAMS'?
  CK_NSS_IKE1_APP_B_PRF_DERIVE_PARAMS dparams = {
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  CK_NSS_IKE1_PRF_DERIVE_PARAMS
/root/rpmbuild/BUILD/libreswan-3.32/lib/libswan/ike_alg_prf_ikev1_nss_ops.c:229:3: error: field name not in record or union initializer
   .prfMechanism = prf->nss.mechanism,
   ^
/root/rpmbuild/BUILD/libreswan-3.32/lib/libswan/ike_alg_prf_ikev1_nss_ops.c:229:3: note: (near initialization for 'dparams')
/root/rpmbuild/BUILD/libreswan-3.32/lib/libswan/ike_alg_prf_ikev1_nss_ops.c:230:3: error: field name not in record or union initializer
   .bHasKeygxy = g_xy != NULL,
   ^
/root/rpmbuild/BUILD/libreswan-3.32/lib/libswan/ike_alg_prf_ikev1_nss_ops.c:230:3: note: (near initialization for 'dparams')
/root/rpmbuild/BUILD/libreswan-3.32/lib/libswan/ike_alg_prf_ikev1_nss_ops.c:230:17: error: excess elements in scalar initializer [-Werror]
   .bHasKeygxy = g_xy != NULL,
                 ^~~~
/root/rpmbuild/BUILD/libreswan-3.32/lib/libswan/ike_alg_prf_ikev1_nss_ops.c:230:17: note: (near initialization for 'dparams')
/root/rpmbuild/BUILD/libreswan-3.32/lib/libswan/ike_alg_prf_ikev1_nss_ops.c:231:3: error: field name not in record or union initializer
   .hKeygxy = g_xy != NULL ? PK11_GetSymKeyHandle(g_xy) : 0,
   ^
/root/rpmbuild/BUILD/libreswan-3.32/lib/libswan/ike_alg_prf_ikev1_nss_ops.c:231:3: note: (near initialization for 'dparams')
/root/rpmbuild/BUILD/libreswan-3.32/lib/libswan/ike_alg_prf_ikev1_nss_ops.c:231:14: error: excess elements in scalar initializer [-Werror]
   .hKeygxy = g_xy != NULL ? PK11_GetSymKeyHandle(g_xy) : 0,
              ^~~~
/root/rpmbuild/BUILD/libreswan-3.32/lib/libswan/ike_alg_prf_ikev1_nss_ops.c:231:14: note: (near initialization for 'dparams')
/root/rpmbuild/BUILD/libreswan-3.32/lib/libswan/ike_alg_prf_ikev1_nss_ops.c:232:3: error: field name not in record or union initializer
   .pExtraData = extra, /* protocol | SPI | Ni_b | Nr_b */
   ^
/root/rpmbuild/BUILD/libreswan-3.32/lib/libswan/ike_alg_prf_ikev1_nss_ops.c:232:3: note: (near initialization for 'dparams')
/root/rpmbuild/BUILD/libreswan-3.32/lib/libswan/ike_alg_prf_ikev1_nss_ops.c:232:17: error: excess elements in scalar initializer [-Werror]
   .pExtraData = extra, /* protocol | SPI | Ni_b | Nr_b */
                 ^~~~~
/root/rpmbuild/BUILD/libreswan-3.32/lib/libswan/ike_alg_prf_ikev1_nss_ops.c:232:17: note: (near initialization for 'dparams')
/root/rpmbuild/BUILD/libreswan-3.32/lib/libswan/ike_alg_prf_ikev1_nss_ops.c:233:3: error: field name not in record or union initializer
   .ulExtraDataLen = extra_size,
   ^
/root/rpmbuild/BUILD/libreswan-3.32/lib/libswan/ike_alg_prf_ikev1_nss_ops.c:233:3: note: (near initialization for 'dparams')
/root/rpmbuild/BUILD/libreswan-3.32/lib/libswan/ike_alg_prf_ikev1_nss_ops.c:233:21: error: excess elements in scalar initializer [-Werror]
   .ulExtraDataLen = extra_size,
                     ^~~~~~~~~~
/root/rpmbuild/BUILD/libreswan-3.32/lib/libswan/ike_alg_prf_ikev1_nss_ops.c:233:21: note: (near initialization for 'dparams')
cc1: all warnings being treated as errors
make[3]: *** [ike_alg_prf_ikev1_nss_ops.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [all] Error 2
make[2]: Leaving directory `/root/rpmbuild/BUILD/libreswan-3.32/lib/libswan'
make[1]: *** [recursive-all] Error 2
make[1]: Leaving directory `/root/rpmbuild/BUILD/libreswan-3.32/lib'
make: *** [recursive-all] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.jpZlrU (%build)

```

**Comment by sirajka** [comment]
@mastertheknife in issue 340 suggested the following alternative but that failed too


```
bash-4.2# rpm -ihv https://download.libreswan.org/binaries/rhel/7/libreswan-release-7-1.noarch.rpm
Retrieving https://download.libreswan.org/binaries/rhel/7/libreswan-release-7-1.noarch.rpm
warning: /var/tmp/rpm-tmp.XBNsMs: Header V4 RSA/SHA512 Signature, key ID b30fc6f9: NOKEY
Updating / installing...
   1:libreswan-3.32-1.el7             ################################# [100%]
warning: user mockbuild does not exist - using root
warning: group mockbuild does not exist - using root
warning: user mockbuild does not exist - using root
warning: group mockbuild does not exist - using root
warning: user mockbuild does not exist - using root
warning: group mockbuild does not exist - using root
warning: user mockbuild does not exist - using root
warning: group mockbuild does not exist - using root
warning: user mockbuild does not exist - using root
warning: group mockbuild does not exist - using root

bash-4.2# rpm -ql libreswan-3.32-1.el7
package libreswan-3.32-1.el7 is not installed
bash-4.2# 
```

**Comment by sirajka** [comment]
Got it to work - thanks to @mastertheknife
by
`yum uninstall openswan`
and
`rpm -ihv https://download.libreswan.org/binaries/rhel/7/x86_64/libreswan-3.32-1.el7.x86_64.rpm`
