### PR TITLE
Build fixes

### PR DESCRIPTION
**Pull request by ojab**
First commit fixes build without pam:
```
/tmp/libreswan/programs/pluto/ikev2_parent.c:82:24: error: field ‘pam’ has incomplete type
  struct pam_thread_arg pam; /* writable inside thread */
                        ^
/tmp/libreswan/programs/pluto/ikev2_parent.c: At top level:
/tmp/libreswan/programs/pluto/ikev2_parent.c:96:33: error: ‘pluto_v2_pam_helpers’ defined but not used [-Werror=unused-variable]
 static struct ikev2_pam_helper *pluto_v2_pam_helpers = NULL;
                                 ^
cc1: all warnings being treated as errors
```

second commit fixes build with gcc-4.9+
```
/tmp/libreswan/programs/pluto/ikev2_parent.c:2434:21: error: variable ‘c’ set but not used [-Werror=unused-but-set-variable]
  struct connection *c = st->st_connection;
                     ^
cc1: all warnings being treated as errors
../../../mk/depend.mk:28: recipe for target 'ikev2_parent.o' failed
```

### CODE REVIEW

**Comment by letoams** [comment]
(changed the last fix part as it was wrong, sorry)
