### ISSUE TITLE
libreswan main fail to build with gcc-4.8.5

### ISSUE THREAD

**Issue by bleve** [libreswan/libreswan#1235]
Log from failing build:

```
In file included from /builddir/build/BUILD/libreswan-4.12/programs/pluto/impair_message.c:20:0:
/builddir/build/BUILD/libreswan-4.12/programs/pluto/impair_message.c: In function 'drip_outbound':
/builddir/build/BUILD/libreswan-4.12/programs/pluto/impair_message.c:352:22: error: 'errno' undeclared (first use in this function)
   llog_error(logger, errno,
                      ^
../../include/lswlog.h:294:12: note: in definition of macro 'llog_error'
   int e_ = ERRNO; /* save value across va args */  \
            ^
/builddir/build/BUILD/libreswan-4.12/programs/pluto/impair_message.c:352:22: note: each undeclared identifier is reported only once for each function it appears in
   llog_error(logger, errno,
                      ^
../../include/lswlog.h:294:12: note: in definition of macro 'llog_error'
   int e_ = ERRNO; /* save value across va args */  \
            ^

```

Bisect result:

ae758f9b5a8770de19c600802ea8d4dfe56c42ba is the first bad commit
