### ISSUE TITLE
3.21 fails to build on Debian 7 and Ubuntu 12.04

### ISSUE THREAD

**Issue by hwdsl2** [libreswan/libreswan#121]
Detailed error during compilation:

```
In file included from /opt/src/libreswan-3.21/programs/pluto/linux-copy/linux/xfrm.h:4:0,
                 from /opt/src/libreswan-3.21/programs/pluto/kernel_netlink.c:52:
/usr/include/linux/in6.h:30:8: error: redefinition of ‘struct in6_addr’
/usr/include/netinet/in.h:198:8: note: originally defined here
/usr/include/linux/in6.h:46:8: error: redefinition of ‘struct sockaddr_in6’
/usr/include/netinet/in.h:239:8: note: originally defined here
/usr/include/linux/in6.h:54:8: error: redefinition of ‘struct ipv6_mreq’
/usr/include/netinet/in.h:275:8: note: originally defined here
make[3]: *** [kernel_netlink.o] Error 1
make[2]: *** [local-base] Error 2
make[1]: *** [recursive-all] Error 2
make: *** [recursive-all] Error 2
```

Looks like this commit may be related:   
https://github.com/libreswan/libreswan/commit/60ff0368a97e713b5d576893dc9bb3c7eedcf92c

Please check. Are these OS no longer being supported by Libreswan?

**Comment by hwdsl2** [comment]
**Update:** I edited "programs/pluto/linux-copy/linux/xfrm.h" and replaced `#include <linux/in6.h>` with `#include <netinet/in.h>` [1], and it compiled successfully on both OS.

[1] http://blog.csdn.net/xc889078/article/details/8796920

**Comment by letoams** [comment]
It's fixed in a later commit, check the master branch on github

**Comment by hwdsl2** [comment]
Thank you for the quick response. I tested the latest master branch on Ubuntu 12.04/Debian 7, unfortunately it shows the same error as stated above.

**Comment by bleve** [comment]
https://libreswan.org/wiki/Compiling_libreswawn_3.21

That is really complicated and there is no simple fix.

**Comment by letoams** [comment]
You can now set USE_GLIBC_KERN_FLIP_HEADERS=true either in a new file Makefile.inc.local or change the existing entry in mk/config.mk to say true. This will flip the headers on those systems where this is still needed. I hope we did manage to make it work for most modern systems out of the box now.
