### ISSUE TITLE
Libreswan 4.8 failed to compile on Alpine Linux 3.16

### ISSUE THREAD

**Issue by hwdsl2** [libreswan/libreswan#880]
Libreswan 4.8 compilation error on Alpine Linux 3.16 (and possibly other OSes, not yet tested). This used to work for Libreswan 4.7 with `USE_GLIBC_KERN_FLIP_HEADERS=true`, but this flag was dropped in Libreswan 4.8. Related commits:
https://github.com/libreswan/libreswan/commit/948e78704790dcb4e505f8af6f2ededfe1e4bb8e
https://github.com/libreswan/libreswan/commit/43465f56dd778a9b880bda53fc035f715f61e178

Libreswan 4.7 compiled fine with `USE_GLIBC_KERN_FLIP_HEADERS=true`.

```
In file included from /opt/src/libreswan-4.8/programs/pluto/state.h:38,
                 from /opt/src/libreswan-4.8/programs/pluto/kernel_xfrm.c:68:
/usr/include/netinet/in.h:23:8: error: redefinition of 'struct in6_addr'
   23 | struct in6_addr {
      |        ^~~~~~~~
In file included from /opt/src/libreswan-4.8/programs/pluto/linux-copy/linux/xfrm.h:5,
                 from /opt/src/libreswan-4.8/programs/pluto/kernel_xfrm.c:60:
/usr/include/linux/in6.h:33:8: note: originally defined here
   33 | struct in6_addr {
      |        ^~~~~~~~
In file included from /opt/src/libreswan-4.8/programs/pluto/state.h:38,
                 from /opt/src/libreswan-4.8/programs/pluto/kernel_xfrm.c:68:
/usr/include/netinet/in.h:34:8: error: redefinition of 'struct sockaddr_in6'
   34 | struct sockaddr_in6 {
      |        ^~~~~~~~~~~~
In file included from /opt/src/libreswan-4.8/programs/pluto/linux-copy/linux/xfrm.h:5,
                 from /opt/src/libreswan-4.8/programs/pluto/kernel_xfrm.c:60:
/usr/include/linux/in6.h:50:8: note: originally defined here
   50 | struct sockaddr_in6 {
      |        ^~~~~~~~~~~~
In file included from /opt/src/libreswan-4.8/programs/pluto/state.h:38,
                 from /opt/src/libreswan-4.8/programs/pluto/kernel_xfrm.c:68:
/usr/include/netinet/in.h:42:8: error: redefinition of 'struct ipv6_mreq'
   42 | struct ipv6_mreq {
      |        ^~~~~~~~~
In file included from /opt/src/libreswan-4.8/programs/pluto/linux-copy/linux/xfrm.h:5,
                 from /opt/src/libreswan-4.8/programs/pluto/kernel_xfrm.c:60:
/usr/include/linux/in6.h:60:8: note: originally defined here
   60 | struct ipv6_mreq {
      |        ^~~~~~~~~
make[3]: *** [../../mk/rules.mk:63: kernel_xfrm.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [../../mk/targets.mk:69: base] Error 2
make[1]: *** [../mk/targets.mk:69: recursive-base] Error 2
make: *** [/opt/src/libreswan-4.8/mk/targets.mk:69: recursive-base] Error 2
```

@cagney @letoams 

Any workaround possible?

**Comment by hwdsl2** [comment]
Found a workaround for this issue: Edit "programs/pluto/linux-copy/linux/xfrm.h" and replace `#include <linux/in6.h>` with `#include <netinet/in.h>`, and it compiled successfully on Alpine 3.16. This workaround is from my earlier comment back in 2017 [1].

[1] https://github.com/libreswan/libreswan/issues/121#issuecomment-323620160

**Comment by bleve** [comment]
That is obviously wrong change because that is copy of kernel xfrm.h. That means you should create a bug against alpine linux, they have a problem.  Other distros requiring include hack have already been fixed as far as known.

**Comment by hwdsl2** [comment]
Thanks for the response. It compiles fine with that change... Since you said it's wrong, I've reverted the version update and kept hwdsl2/docker-ipsec-vpn-server at Libreswan 4.7 for now.

@bleve Not sure if it's the right place to ask, but how severe is the "crasher when built with USE_NSS_KDF=false"?
https://github.com/libreswan/libreswan/commit/f68c34fabecb0f8972c674906e4df02394bdbbc6

Shall I wait until Libreswan 4.9 (which fixes the crasher) before updating users in hwdsl2/docker-ipsec-vpn-server and hwdsl2/setup-ipsec-vpn?

**Comment by bleve** [comment]
That is good idea. The header problem is libc issue. glibc has fixed it but Alpine seem to have different libc with problematic headers.

**Comment by letoams** [comment]
On Fri, 7 Oct 2022, Lin Song wrote:

> Thanks for the response. It compiles fine with that change... Since you said it's wrong, I've reverted the version update and kept
> hwdsl2/docker-ipsec-vpn-server at Libreswan 4.7 for now.
> 
> @bleve Not sure if it's the right place to ask, but how severe is the "crasher when built with USE_NSS_KDF=false"?
> f68c34f
> 
> Shall I wait until Libreswan 4.9 (which fixes the crasher) before updating users in hwdsl2/docker-ipsec-vpn-server and hwdsl2/setup-ipsec-vpn?

Either use the patch or wait for 4.9. We will likely release it in 1-2
weeks. We do want some delay and testing as post release, developers
tend to push things into the tree they had on hold, and we want to ensure
those changes see enough testing as well.

**Comment by hwdsl2** [comment]
@letoams Sounds good, I'll probably wait for 4.9. For this issue with compilation on Alpine, I think it uses musl libc not glibc. Since this is not really a Libreswan bug I'll close this.

**Comment by cagney** [comment]
libreswan really should not be including <netinet/in.h> and <linux/xfrm.h> in the same file

**Comment by cagney** [comment]
Please try mainline, but rather than modifying `linux-copy/linux/xfrm.h`, try adding `#include <netinet/in.h` to `kernel_xfrm.c` just before `<linux/xfrm.h> is included.

**Comment by hwdsl2** [comment]
@cagney Thanks for the fix. With the latest mainline and adding `#include <netinet/in.h>` to `kernel_xfrm.c` as you mentioned, there are some new errors:
```
In file included from ../../include/ip_protocol.h:23,
                 from ../../include/ip_protoport.h:26,
                 from ../../include/ip_endpoint.h:26,
                 from /opt/src/libreswan-main/programs/pluto/connections.h:37,
                 from /opt/src/libreswan-main/programs/pluto/kernel_xfrm_interface.c:40:
/usr/include/netinet/in.h:23:8: error: redefinition of 'struct in6_addr'
   23 | struct in6_addr {
      |        ^~~~~~~~
In file included from /opt/src/libreswan-main/programs/pluto/linux-copy/linux/xfrm.h:5,
                 from ../../include/netlink_attrib.h:4,
                 from /opt/src/libreswan-main/programs/pluto/kernel_xfrm_interface.c:39:
/usr/include/linux/in6.h:33:8: note: originally defined here
   33 | struct in6_addr {
      |        ^~~~~~~~
In file included from ../../include/ip_protocol.h:23,
                 from ../../include/ip_protoport.h:26,
                 from ../../include/ip_endpoint.h:26,
                 from /opt/src/libreswan-main/programs/pluto/connections.h:37,
                 from /opt/src/libreswan-main/programs/pluto/kernel_xfrm_interface.c:40:
/usr/include/netinet/in.h:34:8: error: redefinition of 'struct sockaddr_in6'
   34 | struct sockaddr_in6 {
      |        ^~~~~~~~~~~~
In file included from /opt/src/libreswan-main/programs/pluto/linux-copy/linux/xfrm.h:5,
                 from ../../include/netlink_attrib.h:4,
                 from /opt/src/libreswan-main/programs/pluto/kernel_xfrm_interface.c:39:
/usr/include/linux/in6.h:50:8: note: originally defined here
   50 | struct sockaddr_in6 {
      |        ^~~~~~~~~~~~
In file included from ../../include/ip_protocol.h:23,
                 from ../../include/ip_protoport.h:26,
                 from ../../include/ip_endpoint.h:26,
                 from /opt/src/libreswan-main/programs/pluto/connections.h:37,
                 from /opt/src/libreswan-main/programs/pluto/kernel_xfrm_interface.c:40:
/usr/include/netinet/in.h:42:8: error: redefinition of 'struct ipv6_mreq'
   42 | struct ipv6_mreq {
      |        ^~~~~~~~~
In file included from /opt/src/libreswan-main/programs/pluto/linux-copy/linux/xfrm.h:5,
                 from ../../include/netlink_attrib.h:4,
                 from /opt/src/libreswan-main/programs/pluto/kernel_xfrm_interface.c:39:
/usr/include/linux/in6.h:60:8: note: originally defined here
   60 | struct ipv6_mreq {
      |        ^~~~~~~~~
make[3]: *** [../../mk/rules.mk:63: kernel_xfrm_interface.o] Error 1
make[2]: *** [../../mk/targets.mk:69: base] Error 2
make[2]: Leaving directory '/opt/src/libreswan-main/programs/pluto'
make[1]: *** [../mk/targets.mk:69: recursive-base] Error 2
make[1]: Leaving directory '/opt/src/libreswan-main/programs'
make: *** [/opt/src/libreswan-main/mk/targets.mk:69: recursive-base] Error 2
```

On the other hand, adding `#include <netinet/in.h>` before the line `#include <linux/in6.h>` in `linux-copy/linux/xfrm.h` does fix the build on Alpine 3.16. But that is likely wrong as @bleve said earlier.

**Comment by cagney** [comment]
So the good news is that `lib/libswan` and `programs/pluto/iface*` compiled which means the issue is confined to linux specific files.  For kernel_xfrm_interface.c, can you again try adding `#include <netinet/in.h>` at the top of the file?

To @bleve's point `linux-copy/linux/xfrm.h` shouldn't be modified, and distros should be able to build using USE_XFRM_HEADER_COPY=false (i.e., use installed linux kernel headers) should work.

Did you ping musl upstream about this problem?  I guess musl should honour this from glibc's `<netinet/in.h>`):
```
/* If __USE_KERNEL_IPV6_DEFS is 1 then the user has included the kernel
   network headers first and we should use those ABI-identical definitions
   instead of our own, otherwise 0.  */
#if !__USE_KERNEL_IPV6_DEFS
```

For libreswan, I'm wondering if we should force the use of `<netinet/in.h>`.

**Comment by hwdsl2** [comment]
@cagney I can try that modification tonight. I have not pinged musl upstream as I am not sure how to describe this issue to them.

**Comment by cagney** [comment]
Thanks.  I'd just point them at this bug.

**Comment by cagney** [comment]
Can you please try mainline without any changes, we're testing e16b8d169148d9b1b367fe55c96111ed7069ea10

**Comment by hwdsl2** [comment]
@cagney I'm happy to report that mainline (as of now) compiles successfully on Alpine 3.16 without any changes. I did not test on other Linux distributions.

**Comment by hwdsl2** [comment]
@cagney No, I have not pinged MUSL upstream yet.
